/* 3GPP UE 프로토콜 스펙 지도 — 데이터
 *
 * 용어 표기 원칙: 스펙·프로토콜 용어는 현업 관행대로 영어로 쓴다.
 *   설명 문장(when)은 한국어를 유지하되, 그 안의 기술용어는 영어로 둔다.
 *
 * ntn 값: 'only'   = NTN 전용 문서
 *         'clause' = 일반 스펙인데 NTN 전용 조항이 있음
 *         null     = NTN 무관
 * side:   'ue' (기본) | 'net' = network 측 문서(참고용)
 * short:  카드 상단에 붙는 짧은 영문 라벨(title의 축약형)
 * kw:     검색 보조 키워드. 한국어 검색어도 함께 넣어 둔다.
 */

const MODULES = [
  { id: 'phy',    name: 'PHY',               desc: 'Physical layer — channels, coding, procedures, measurements' },
  { id: 'mac',    name: 'MAC',               desc: 'Scheduling, HARQ, random access' },
  { id: 'sdap',   name: 'SDAP',              desc: 'QoS flow → DRB mapping — NR only, no LTE counterpart' },
  { id: 'pdcp',   name: 'PDCP',              desc: 'Header compression, ciphering & integrity, reordering, duplication' },
  { id: 'rlc',    name: 'RLC',               desc: 'ARQ retransmission, segmentation and reassembly' },
  { id: 'rrc',    name: 'RRC · Mobility',    desc: 'Connection control, cell selection/reselection, handover, RRM' },
  { id: 'uecap',  name: 'UE Capability',     desc: 'What the UE declares it supports' },
  { id: 'nas',    name: 'NAS · Core',        desc: 'Registration, session and mobility management — dialogue with the core network' },
  { id: 'sec',    name: 'Security · USIM',   desc: 'Authentication & key derivation, UICC/USIM interface' },
  { id: 'rf',     name: 'RF · Performance',  desc: 'Tx/Rx requirements, bands, performance' },
  { id: 'ims',    name: 'IMS · Services',    desc: 'VoLTE/VoNR call control and media' },
  { id: 't-com',  name: 'Test — Common',     desc: 'Common test environment and configuration', test: true },
  { id: 't-pct',  name: 'Test — PCT',        desc: 'Protocol conformance test', test: true },
  { id: 't-rrm',  name: 'Test — RRM',        desc: 'Radio resource management conformance test', test: true },
  { id: 't-rct',  name: 'Test — RCT',        desc: 'RF conformance test', test: true }
];

const SPECS = [
  /* ── PHY ───────────────────────────────────────────── */
  { id: '38.201', m: 'phy', s: 'NR', peer: '36.201', rel: 'Rel-15~',
    title: 'NR; Physical layer; General description',
    short: 'PHY general description',
    when: 'PHY 문서들(211~215)이 각각 무엇을 다루는지 길을 잃었을 때 돌아오는 지도.' },
  { id: '38.211', m: 'phy', s: 'NR', peer: '36.211', rel: 'Rel-15~',
    kw: 'frame structure numerology resource grid DMRS SSB 물리채널 변조',
    title: 'NR; Physical channels and modulation',
    short: 'Physical channels and modulation',
    when: 'Frame structure, numerology, resource grid, DMRS·SSB 위치를 확인할 때.' },
  { id: '38.212', m: 'phy', s: 'NR', peer: '36.212', rel: 'Rel-15~',
    kw: 'DCI UCI polar LDPC channel coding 다중화 부호화',
    title: 'NR; Multiplexing and channel coding',
    short: 'Multiplexing and channel coding',
    when: 'DCI/UCI 필드 구성과 bit width, Polar·LDPC coding 절차를 볼 때. DCI format parsing의 근거.' },
  { id: '38.213', m: 'phy', s: 'NR', peer: '36.213', rel: 'Rel-15~', ntn: 'clause',
    kw: 'RACH PRACH random access power control PUCCH beam TA timing advance K_offset 랜덤액세스 전력제어 타이밍',
    ntnNote: '<b>Timing pre-compensation (시간축)</b> — N<sub>TA,adjUE</sub> 기반 양방향 propagation delay 보상, <code>cellSpecificKoffset</code> / K<sub>UE,offset</sub> 적용. <b>Frequency (Doppler) pre-compensation은 여기가 아니라 38.300 §16.14.2.2</b>',
    title: 'NR; Physical layer procedures for control',
    short: 'PHY procedures for control',
    when: '★ Random access 절차, power control, PUCCH resource 결정, beam management를 볼 때. NTN timing 보정(TA·K_offset)도 여기 — 단 Doppler는 38.300.' },
  { id: '38.214', m: 'phy', s: 'NR', peer: '36.213', rel: 'Rel-15~',
    kw: 'PDSCH PUSCH MCS TBS CSI resource allocation 자원할당',
    title: 'NR; Physical layer procedures for data',
    short: 'PHY procedures for data',
    when: 'PDSCH/PUSCH resource allocation, MCS·TBS 계산, CSI reporting 절차.' },
  { id: '38.215', m: 'phy', s: 'NR', peer: '36.214', rel: 'Rel-15~',
    kw: 'RSRP RSRQ SINR measurement 측정',
    title: 'NR; Physical layer measurements',
    short: 'PHY measurements',
    when: 'RSRP/RSRQ/SINR의 정확한 정의가 필요할 때. Measurement 값 불일치 디버깅의 출발점.' },
  { id: '36.201', m: 'phy', s: 'LTE', peer: '38.201', rel: 'Rel-8~',
    title: 'E-UTRA; LTE physical layer; General description',
    short: 'LTE PHY general description',
    when: 'LTE PHY 문서 구성 파악용.' },
  { id: '36.211', m: 'phy', s: 'LTE', peer: '38.211', rel: 'Rel-8~',
    kw: 'PSS SSS reference signal NB-IoT NPBCH NPDCCH NPUSCH 물리채널',
    title: 'E-UTRA; Physical channels and modulation',
    short: 'LTE physical channels and modulation',
    when: 'LTE frame structure, reference signal, PSS/SSS. NB-IoT physical channel(NPBCH·NPDCCH·NPUSCH)도 여기 포함.' },
  { id: '36.212', m: 'phy', s: 'LTE', peer: '38.212', rel: 'Rel-8~',
    kw: 'DCI turbo coding NB-IoT 부호화',
    title: 'E-UTRA; Multiplexing and channel coding',
    short: 'LTE multiplexing and channel coding',
    when: 'LTE DCI format과 Turbo coding. NB-IoT coding 포함.' },
  { id: '36.213', m: 'phy', s: 'LTE', peer: '38.213', rel: 'Rel-8~',
    title: 'E-UTRA; Physical layer procedures',
    short: 'LTE PHY procedures',
    when: 'LTE는 control/data 절차가 한 문서에 있다(NR은 38.213/38.214로 분리). 이 차이가 자주 헷갈린다.' },
  { id: '36.214', m: 'phy', s: 'LTE', peer: '38.215', rel: 'Rel-8~',
    kw: 'RSRP RSRQ measurement 측정',
    title: 'E-UTRA; Physical layer; Measurements',
    short: 'LTE PHY measurements',
    when: 'LTE RSRP/RSRQ 정의.' },

  /* ── MAC ───────────────────────────────────────────── */
  { id: '38.321', m: 'mac', s: 'NR', peer: '36.321', rel: 'Rel-15~', ntn: 'clause',
    kw: 'MAC PDU LCID BSR PHR DRX random access 랜덤액세스',
    ntnNote: 'NTN random access 적응 — 확장된 RA response window, HARQ disable 옵션',
    title: 'NR; Medium Access Control (MAC) protocol specification',
    short: 'MAC protocol',
    when: '★ MAC PDU format, LCID 값, BSR/PHR, DRX timer, RA 절차. Log 분석에서 가장 자주 펼침.' },
  { id: '36.321', m: 'mac', s: 'LTE', peer: '38.321', rel: 'Rel-8~', ntn: 'clause',
    kw: 'MAC PDU LCID DRX eDRX NB-IoT',
    ntnNote: 'IoT NTN random access 적응(Rel-17~)',
    title: 'E-UTRA; Medium Access Control (MAC) protocol specification',
    short: 'LTE MAC protocol',
    when: 'LTE MAC PDU·LCID·DRX. NB-IoT DRX/eDRX 동작도 여기.' },

  /* ── SDAP (NR 전용) ────────────────────────────────── */
  { id: '37.324', m: 'sdap', s: 'NR', rel: 'Rel-15~',
    kw: 'QoS flow DRB mapping reflective QoS',
    title: 'E-UTRA and NR; Service Data Adaptation Protocol (SDAP) specification',
    short: 'SDAP protocol',
    when: 'QoS flow → DRB mapping. <b>NR에만 있는 layer</b>라 LTE 경험자가 처음 만나면 낯설다. 37.xxx 시리즈인 것도 주의(38.xxx가 아니다).' },

  /* ── PDCP ──────────────────────────────────────────── */
  { id: '38.323', m: 'pdcp', s: 'NR', peer: '36.323', rel: 'Rel-15~',
    kw: 'ROHC header compression integrity ciphering reordering duplication 암호화',
    title: 'NR; Packet Data Convergence Protocol (PDCP) specification',
    short: 'PDCP protocol',
    when: 'Header compression(ROHC), integrity protection·ciphering, reordering, duplication.' },
  { id: '36.323', m: 'pdcp', s: 'LTE', peer: '38.323', rel: 'Rel-8~',
    kw: 'ROHC header compression 암호화',
    title: 'E-UTRA; Packet Data Convergence Protocol (PDCP) specification',
    short: 'LTE PDCP protocol',
    when: 'LTE PDCP, ROHC.' },

  /* ── RLC ───────────────────────────────────────────── */
  { id: '38.322', m: 'rlc', s: 'NR', peer: '36.322', rel: 'Rel-15~',
    kw: 'AM UM ARQ status report segmentation reassembly concatenation 재전송',
    title: 'NR; Radio Link Control (RLC) protocol specification',
    short: 'RLC protocol',
    when: 'AM/UM 동작, status report, reassembly. NR RLC는 concatenation이 없다는 점이 LTE와 큰 차이.' },
  { id: '36.322', m: 'rlc', s: 'LTE', peer: '38.322', rel: 'Rel-8~',
    kw: 'AM UM ARQ concatenation 재전송',
    title: 'E-UTRA; Radio Link Control (RLC) protocol specification',
    short: 'LTE RLC protocol',
    when: 'LTE RLC AM/UM. Concatenation이 있다는 점이 NR과 다르다.' },

  /* ── RRC · Mobility ────────────────────────────────── */
  { id: '38.300', m: 'rrc', s: 'NR', peer: '36.300', rel: 'Rel-15~', ntn: 'clause',
    kw: 'stage 2 overall description architecture Doppler frequency pre-compensation 도플러 사전보상 총론',
    ntnNote: '§16.14 NTN 전반. <b>§16.14.2.2 Timing Advance and Frequency Pre-compensation</b> — UE가 satellite ephemeris와 자기 위치로 <b>Doppler shift를 스스로 계산해 uplink carrier를 pre-compensate</b>한다고 규정한 곳. 38.101-5 §6.4.1이 이 조항을 직접 참조한다.',
    title: 'NR; NR and NG-RAN Overall description; Stage-2',
    short: 'NR · NG-RAN overall description (Stage-2)',
    when: '★ 개별 layer 문서로 들어가기 전에 전체 구조를 잡는 문서. "이 기능이 어느 layer 소관인가"의 1차 답이 대개 여기. NTN uplink sync의 규범적 출처.' },
  { id: '36.300', m: 'rrc', s: 'LTE', peer: '38.300', rel: 'Rel-8~',
    kw: 'stage 2 overall description architecture 총론',
    title: 'E-UTRA and E-UTRAN; Overall description; Stage 2',
    short: 'E-UTRA · E-UTRAN overall description (Stage 2)',
    when: 'LTE 전체 구조 조망. Layer 간 기능 분담을 확인할 때.' },
  { id: '38.331', m: 'rrc', s: 'NR', peer: '36.331', rel: 'Rel-15~', ntn: 'clause',
    kw: 'RRC ASN.1 SIB SIB19 handover measurement reconfiguration 핸드오버 측정 시스템정보',
    ntnNote: 'SIB19 / <code>NTN-Config-r17</code> — <code>ephemerisInfo</code>, <code>epochTime</code>, <code>ta-Info-r17</code>(하위 <code>ta-Common</code> / <code>ta-CommonDrift</code> / <code>ta-CommonDriftVariant</code>), <code>cellSpecificKoffset-r17</code>, <code>ntn-UlSyncValidityDuration</code>, <code>t-Service</code>, <code>referenceLocation</code>, <code>distanceThresh</code>, <code>ntn-PolarizationDL/UL</code>, <code>ntn-NeighCellConfigList</code>',
    title: 'NR; Radio Resource Control (RRC); Protocol specification',
    short: 'RRC protocol',
    when: '★★ UE 개발에서 가장 자주 펼치는 문서. 모든 ASN.1 정의, SIB 구성, measurement configuration, handover 메시지가 여기.' },
  { id: '38.304', m: 'rrc', s: 'NR', peer: '36.304', rel: 'Rel-15~', ntn: 'clause',
    kw: 'cell selection reselection paging PLMN idle inactive 셀선택 재선택 페이징',
    ntnNote: 'NTN cell selection/reselection — 위치 기반 조건, service time(<code>t-Service</code>) 고려',
    title: 'NR; User Equipment (UE) procedures in Idle mode and in RRC Inactive state',
    short: 'UE procedures in Idle / RRC Inactive',
    when: 'Cell selection·reselection 기준(S-criterion, R-criterion), PLMN selection, paging 수신 시점 계산.' },
  { id: '38.133', m: 'rrc', s: 'NR', peer: '36.133', rel: 'Rel-15~',
    kw: 'RRM measurement accuracy handover delay cell identification 측정 이동성',
    title: 'NR; Requirements for support of radio resource management',
    short: 'RRM requirements',
    when: 'Measurement accuracy, cell identification time, handover delay 요구. "얼마나 빨리/정확히" 해야 하는지의 근거. 38.533 test의 뿌리.' },
  { id: '36.331', m: 'rrc', s: 'LTE', peer: '38.331', rel: 'Rel-8~', ntn: 'clause',
    kw: 'RRC ASN.1 SIB NB-IoT 핸드오버 측정',
    ntnNote: 'IoT NTN 관련 SIB·configuration(Rel-17~)',
    title: 'E-UTRA; Radio Resource Control (RRC); Protocol specification',
    short: 'LTE RRC protocol',
    when: 'LTE RRC ASN.1 전체. NB-IoT RRC도 이 문서 안에 포함.' },
  { id: '36.304', m: 'rrc', s: 'LTE', peer: '38.304', rel: 'Rel-8~',
    kw: 'cell selection reselection paging 셀선택 페이징',
    title: 'E-UTRA; User Equipment (UE) procedures in idle mode',
    short: 'LTE UE procedures in Idle mode',
    when: 'LTE cell selection·reselection, paging.' },
  { id: '36.133', m: 'rrc', s: 'LTE', peer: '38.133', rel: 'Rel-8~',
    kw: 'RRM measurement mobility 측정 이동성',
    title: 'E-UTRA; Requirements for support of radio resource management',
    short: 'LTE RRM requirements',
    when: 'LTE measurement·mobility 성능 요구. 36.521-3 test의 뿌리.' },

  /* ── UE Capability ─────────────────────────────────── */
  { id: '38.306', m: 'uecap', s: 'NR', peer: '36.306', rel: 'Rel-15~',
    kw: 'featureSets featureSetCombination capability 능력',
    title: 'NR; User Equipment (UE) radio access capabilities',
    short: 'UE radio access capabilities',
    when: '★ 어떤 capability parameter가 있고 값의 의미가 무엇인지. <code>featureSets</code> / <code>featureSetCombination</code> 구조가 NR capability의 핵심.',
    xref: 'Signalling은 38.331(UECapabilityInformation), test 선언은 38.508-2(ICS)' },
  { id: '38.822', m: 'uecap', s: 'NR', rel: 'Rel-15~', tr: true,
    kw: 'feature list release capability',
    title: 'NR; User Equipment (UE) feature list',
    short: 'NR UE feature list',
    when: 'Release별로 어떤 feature가 있고 어느 capability parameter에 대응하는지 훑을 때. TR이지만 실무 참조도가 높다.' },
  { id: '38.307', m: 'uecap', s: 'NR', peer: '36.307', rel: 'Rel-15~',
    kw: 'release independent band',
    title: 'NR; Requirements on User Equipments (UEs) supporting a release-independent frequency band',
    short: 'Release-independent band support requirements',
    when: '나중 release에서 추가된 band를 이전 release UE가 지원할 때의 규칙.' },
  { id: '36.306', m: 'uecap', s: 'LTE', peer: '38.306', rel: 'Rel-8~',
    kw: 'UE category NB1 NB2 capability 능력',
    title: 'E-UTRA; User Equipment (UE) radio access capabilities',
    short: 'LTE UE radio access capabilities',
    when: 'UE category와 capability parameter. NB-IoT category(NB1/NB2)도 여기.',
    xref: 'Signalling은 36.331(UE-EUTRA-Capability)' },
  { id: '36.307', m: 'uecap', s: 'LTE', peer: '38.307', rel: 'Rel-8~',
    kw: 'release independent band',
    title: 'E-UTRA; Requirements on User Equipments (UEs) supporting a release-independent frequency band',
    short: 'LTE release-independent band',
    when: 'LTE band 추가 시 release 호환 규칙.' },

  /* ── NAS · Core ────────────────────────────────────── */
  { id: '24.501', m: 'nas', s: 'NR', peer: '24.301', rel: 'Rel-15~', ntn: 'clause',
    kw: '5GMM 5GSM registration PDU session T3510 등록 세션',
    ntnNote: '5GS NTN 관련 절차·timer 조정',
    title: 'Non-Access-Stratum (NAS) protocol for 5G System (5GS); Stage 3',
    short: '5GS NAS protocol',
    when: '★ Registration/PDU session 절차, 5GMM·5GSM 메시지와 IE, timer(T3510 등). 5G UE NAS 개발의 본문.' },
  { id: '23.501', m: 'nas', s: 'NR', peer: '23.401', rel: 'Rel-15~', ntn: 'clause',
    kw: 'architecture satellite RAT type tracking area 아키텍처',
    ntnNote: '§5.4.10 satellite access 식별·제한, §5.4.11 satellite access의 5GS 통합 — satellite RAT type, network selection, Tracking Area 처리, Forbidden/Service Area mobility restriction. (Transparent/regenerative payload 구분은 여기가 아니라 TR 38.821)',
    title: 'System architecture for the 5G System (5GS)',
    short: '5GS system architecture',
    when: '용어와 개념의 출처. "이 기능이 왜 이렇게 설계됐나"를 물을 때.' },
  { id: '23.502', m: 'nas', s: 'NR', rel: 'Rel-15~',
    kw: 'procedures call flow end-to-end 절차',
    title: 'Procedures for the 5G System (5GS)',
    short: '5GS procedures',
    when: 'UE~gNB~core를 잇는 end-to-end call flow. NAS 메시지가 어떤 맥락에서 오가는지 볼 때.' },
  { id: '24.301', m: 'nas', s: 'LTE', peer: '24.501', rel: 'Rel-8~', ntn: 'clause',
    kw: 'EMM ESM attach TAU service request CIoT NB-IoT 등록',
    ntnNote: 'IoT NTN 관련 timer·절차 조정(Rel-17~)',
    title: 'Non-Access-Stratum (NAS) protocol for Evolved Packet System (EPS); Stage 3',
    short: 'EPS NAS protocol',
    when: '★ EMM/ESM 절차와 메시지. Attach·TAU·Service Request. NB-IoT의 CIoT EPS optimization(control plane CIoT)도 여기.' },
  { id: '23.401', m: 'nas', s: 'LTE', peer: '23.501', rel: 'Rel-8~',
    kw: 'EPS bearer architecture 아키텍처',
    title: 'GPRS enhancements for E-UTRAN access',
    short: 'EPS system architecture',
    when: 'EPS bearer 개념, interface 정의.' },
  { id: '24.008', m: 'nas', s: 'Common', rel: 'Rel-99~', base: true,
    kw: 'layer 3 IE MM GMM CC SM common 공통',
    title: 'Mobile radio interface Layer 3 specification; Core network protocols; Stage 3',
    short: 'L3 core network protocol · common IE',
    when: '★ 24.301과 24.501이 IE 정의를 이 문서에서 참조해 온다. "이 IE 정의가 어디 있지?"의 답이 자주 여기. MM/GMM/CC/SM의 원형.' },
  { id: '23.122', m: 'nas', s: 'Common', rel: 'Rel-99~',
    kw: 'PLMN selection forbidden PLMN manual search idle mode PLMN선택',
    title: 'Non-Access-Stratum (NAS) functions related to Mobile Station (MS) in idle mode',
    short: 'PLMN selection in idle mode',
    when: '★ PLMN selection·reselection, forbidden PLMN list, manual search의 본문. 24.301/24.501 다음으로 자주 펼치는 NAS 문서. Satellite access PLMN selection도 여기.' },
  { id: '24.007', m: 'nas', s: 'Common', rel: 'Rel-99~', base: true,
    kw: 'TLV encoding message format layer 3 부호화',
    title: 'Mobile radio interface signalling layer 3; General aspects',
    short: 'L3 signalling general aspects',
    when: 'L3 메시지의 일반 format과 IE encoding 규칙(T/L/V, TLV 등). 메시지 parser를 직접 만들 때의 근거.' },

  /* ── Security · USIM ───────────────────────────────── */
  { id: '33.501', m: 'sec', s: 'NR', peer: '33.401', rel: 'Rel-15~',
    kw: '5G-AKA SUCI key hierarchy authentication 보안 인증',
    title: 'Security architecture and procedures for 5G System',
    short: '5G security architecture',
    when: '5G-AKA authentication, key hierarchy(K<sub>AUSF</sub>→K<sub>SEAF</sub>→K<sub>AMF</sub>→K<sub>gNB</sub>), SUCI concealment. NAS/AS security activation 절차.' },
  { id: '33.401', m: 'sec', s: 'LTE', peer: '33.501', rel: 'Rel-8~',
    kw: 'EPS-AKA KASME key derivation 보안 인증',
    title: '3GPP System Architecture Evolution (SAE); Security architecture',
    short: 'EPS security architecture',
    when: 'EPS-AKA, K<sub>ASME</sub> 기반 key derivation.' },
  { id: '31.101', m: 'sec', s: 'Common', rel: 'Rel-99~',
    kw: 'UICC APDU terminal interface',
    title: 'UICC-terminal interface; Physical and logical characteristics',
    short: 'UICC – terminal interface',
    when: 'APDU 수준에서 UICC와 대화할 때.' },
  { id: '31.102', m: 'sec', s: 'Common', rel: 'Rel-99~',
    kw: 'USIM EF IMSI LOCI EPSLOCI authentication',
    title: 'Characteristics of the USIM application',
    short: 'USIM application',
    when: '★ EF file 구조(<code>EF_IMSI</code>, <code>EF_LOCI</code>, <code>EF_EPSLOCI</code> 등), authentication command. UE가 USIM에서 무엇을 읽는지.' },

  /* ── RF · Performance ──────────────────────────────── */
  { id: '38.101-1', m: 'rf', s: 'NR', peer: '36.101', rel: 'Rel-15~',
    kw: 'FR1 band power class sensitivity 대역 감도',
    title: 'NR; UE radio transmission and reception; Part 1: Range 1 Standalone',
    short: 'NR UE RF (FR1)',
    when: 'Band 정의, power class, sensitivity. FR1(6GHz 이하) band 확인은 여기.' },
  { id: '38.101-2', m: 'rf', s: 'NR', rel: 'Rel-15~',
    kw: 'FR2 mmWave EIRP band 대역',
    title: 'NR; UE radio transmission and reception; Part 2: Range 2 Standalone',
    short: 'NR UE RF (FR2)',
    when: 'mmWave band. FR1과 요구사항 체계가 다르다(EIRP 기반 등).' },
  { id: '38.101-3', m: 'rf', s: 'NR', rel: 'Rel-15~',
    kw: 'EN-DC interworking dual connectivity 연동',
    title: 'NR; UE radio transmission and reception; Part 3: Range 1 and Range 2 Interworking with other radios',
    short: 'NR UE RF (interworking)',
    when: 'EN-DC 등 LTE-NR 동시 동작 시의 RF 요구사항.' },
  { id: '38.101-4', m: 'rf', s: 'NR', rel: 'Rel-15~',
    kw: 'demodulation performance CSI 성능',
    title: 'NR; UE radio transmission and reception; Part 4: Performance requirements',
    short: 'NR UE performance requirements',
    when: 'Demodulation performance·CSI reporting accuracy 요구.' },
  { id: '38.101-5', m: 'rf', s: 'NR', rel: 'Rel-17~', ntn: 'only',
    kw: 'satellite access NTN RF performance 위성',
    title: 'NR; UE radio transmission and reception; Part 5: Satellite access Radio Frequency (RF) and performance requirements',
    short: 'NTN satellite access UE RF · performance',
    when: 'NTN 전용. Satellite access UE의 RF·performance 요구사항 — 지상망과 별도 Part로 분리되어 있다.' },
  { id: '38.108', m: 'rf', s: 'NR', rel: 'Rel-17~', ntn: 'only', side: 'net',
    kw: 'satellite access node payload 위성 망측',
    title: 'NR; Satellite Access Node radio transmission and reception',
    short: 'NTN Satellite Access Node RF',
    when: 'NTN 전용, network 측 문서. Satellite payload 쪽 요구사항을 확인할 때.' },
  { id: '36.101', m: 'rf', s: 'LTE', peer: '38.101-1', rel: 'Rel-8~',
    kw: 'band power class sensitivity NB-IoT 대역 감도',
    title: 'E-UTRA; User Equipment (UE) radio transmission and reception',
    short: 'LTE UE RF',
    when: 'LTE band·power class·sensitivity. NB-IoT RF 요구사항도 이 문서에 포함.' },

  /* ── IMS · Services ────────────────────────────────── */
  { id: '24.229', m: 'ims', s: 'Common', rel: 'Rel-5~',
    kw: 'SIP SDP VoLTE VoNR registration call setup 호제어',
    title: 'IP multimedia call control protocol based on SIP and SDP; Stage 3',
    short: 'IMS SIP call control',
    when: '★ VoLTE/VoNR registration·call setup SIP 메시지. 매우 두껍고 IETF RFC를 대량 참조하므로 각오하고 펼칠 것.' },
  { id: '26.114', m: 'ims', s: 'Common', rel: 'Rel-7~',
    kw: 'MTSI codec jitter buffer media adaptation 음성품질',
    title: 'IMS; Multimedia telephony; Media handling and interaction',
    short: 'MTSI media handling',
    when: 'Codec negotiation, jitter buffer, media adaptation. 음성 품질 이슈의 근거 문서.' },

  /* ── Test — Common ─────────────────────────────────── */
  { id: '38.508-1', m: 't-com', s: 'NR', peer: '36.508', rel: 'Rel-15~',
    kw: 'common test environment reference configuration 시험환경',
    title: '5GS; UE conformance specification; Part 1: Common test environment',
    short: 'NR common test environment',
    when: '★ Test용 reference configuration·메시지 내용·공통 절차. PCT/RRM/RCT 셋이 모두 이 문서를 참조한다.' },
  { id: '38.508-2', m: 't-com', s: 'NR', rel: 'Rel-15~',
    kw: 'ICS proforma applicability declaration 선언',
    title: '5GS; UE conformance specification; Part 2: Common Implementation Conformance Statement (ICS) proforma',
    short: 'NR common ICS',
    when: 'UE가 "무엇을 지원한다"고 선언하는 표. 이 declaration이 어떤 test case가 적용될지를 결정한다.',
    xref: 'Capability 정의는 38.306' },
  { id: '36.508', m: 't-com', s: 'LTE', peer: '38.508-1', rel: 'Rel-8~',
    kw: 'common test environment 시험환경',
    title: 'E-UTRA and EPC; Common test environments for UE conformance testing',
    short: 'LTE common test environment',
    when: 'LTE test 공통 configuration.' },

  /* ── Test — PCT ────────────────────────────────────── */
  { id: '38.523-1', m: 't-pct', s: 'NR', peer: '36.523-1', rel: 'Rel-15~',
    kw: 'protocol conformance test case 시험케이스',
    title: '5GS; UE conformance specification; Part 1: Protocol',
    short: 'NR protocol test cases',
    when: '★ Test case 본문. UE protocol 개발자가 test 계열에서 가장 자주 보는 문서.' },
  { id: '38.523-2', m: 't-pct', s: 'NR', rel: 'Rel-15~',
    kw: 'applicability test case 적용성',
    title: '5GS; UE conformance specification; Part 2: Applicability of protocol test cases',
    short: 'NR test case applicability',
    when: '어떤 UE에 어떤 test가 적용되는지의 조건표.' },
  { id: '38.523-3', m: 't-pct', s: 'NR', rel: 'Rel-15~',
    kw: 'TTCN test suite 시험장비',
    title: '5GS; UE conformance specification; Part 3: Protocol Test Suites',
    short: 'NR test suites (TTCN)',
    when: '실제 TTCN 구현. Test 장비 동작을 추적할 때.' },
  { id: '36.523-1', m: 't-pct', s: 'LTE', peer: '38.523-1', rel: 'Rel-8~',
    kw: 'protocol conformance test case 시험케이스',
    title: 'E-UTRA and EPC; UE conformance specification; Part 1: Protocol conformance specification',
    short: 'LTE protocol test cases',
    when: 'LTE protocol test 본문.' },
  { id: '36.523-2', m: 't-pct', s: 'LTE', rel: 'Rel-8~',
    kw: 'ICS proforma applicability 적용성',
    title: 'E-UTRA and EPC; UE conformance specification; Part 2: ICS proforma specification',
    short: 'LTE test ICS',
    when: 'LTE applicability declaration.' },
  { id: '36.523-3', m: 't-pct', s: 'LTE', rel: 'Rel-8~',
    kw: 'TTCN test suite',
    title: 'E-UTRA and EPC; UE conformance specification; Part 3: Test suites',
    short: 'LTE test suites (TTCN)',
    when: 'LTE TTCN 구현.' },

  /* ── Test — RRM ────────────────────────────────────── */
  { id: '38.533', m: 't-rrm', s: 'NR', peer: '36.521-3', rel: 'Rel-15~', asym: true,
    kw: 'RRM conformance measurement mobility 측정 이동성',
    title: 'NR; User Equipment (UE) conformance specification; Radio Resource Management (RRM)',
    short: 'NR RRM conformance test',
    when: '★ Measurement·mobility 성능 test. <b>주의: NR은 RRM이 521 시리즈 밖으로 나와 별도 번호(38.533)를 쓴다.</b> LTE(36.521-3)와 체계가 다르다.',
    xref: '요구사항 본문은 38.133' },
  { id: '36.521-3', m: 't-rrm', s: 'LTE', peer: '38.533', rel: 'Rel-8~', asym: true,
    kw: 'RRM conformance measurement mobility 측정 이동성',
    title: 'E-UTRA; UE conformance specification; Radio transmission and reception; Part 3: Radio Resource Management (RRM) conformance testing',
    short: 'LTE RRM conformance test',
    when: 'LTE measurement·mobility test. <b>NR과 달리 521 시리즈 안에 들어 있다.</b>',
    xref: '요구사항 본문은 36.133' },

  /* ── Test — RCT ────────────────────────────────────── */
  { id: '38.521-1', m: 't-rct', s: 'NR', peer: '36.521-1', rel: 'Rel-15~',
    kw: 'FR1 RF conformance',
    title: 'NR; UE conformance specification; Radio transmission and reception; Part 1: Range 1 Standalone',
    short: 'NR RF test (FR1)',
    when: 'FR1 RF conformance test.', xref: '요구사항 본문은 38.101-1' },
  { id: '38.521-2', m: 't-rct', s: 'NR', rel: 'Rel-15~',
    kw: 'FR2 RF conformance mmWave',
    title: 'NR; UE conformance specification; Radio transmission and reception; Part 2: Range 2 Standalone',
    short: 'NR RF test (FR2)',
    when: 'FR2 RF conformance test.', xref: '요구사항 본문은 38.101-2' },
  { id: '38.521-3', m: 't-rct', s: 'NR', rel: 'Rel-15~',
    kw: 'EN-DC interworking RF conformance 연동',
    title: 'NR; UE conformance specification; Radio transmission and reception; Part 3: Range 1 and Range 2 Interworking operation with other radios',
    short: 'NR RF test (interworking)',
    when: 'EN-DC 등 interworking RF test.', xref: '요구사항 본문은 38.101-3' },
  { id: '38.521-4', m: 't-rct', s: 'NR', rel: 'Rel-15~',
    kw: 'demodulation performance conformance 성능',
    title: 'NR; UE conformance specification; Radio transmission and reception; Part 4: Performance',
    short: 'NR performance test',
    when: 'Demodulation performance test.', xref: '요구사항 본문은 38.101-4' },
  { id: '38.521-5', m: 't-rct', s: 'NR', rel: 'Rel-17~', ntn: 'only',
    kw: 'satellite access NTN RF conformance 위성',
    title: 'NR; UE conformance specification; Radio transmission and reception; Part 5: Satellite access Radio Frequency (RF) and performance requirements',
    short: 'NTN satellite access RF test',
    when: 'NTN 전용. 38.101-5의 test 짝 — satellite access UE의 RF·performance conformance test.',
    xref: '요구사항 본문은 38.101-5' },
  { id: '36.521-1', m: 't-rct', s: 'LTE', peer: '38.521-1', rel: 'Rel-8~',
    kw: 'RF conformance',
    title: 'E-UTRA; UE conformance specification; Radio transmission and reception; Part 1: Conformance testing',
    short: 'LTE RF test',
    when: 'LTE RF conformance test.', xref: '요구사항 본문은 36.101' },
  { id: '36.521-2', m: 't-rct', s: 'LTE', rel: 'Rel-8~',
    kw: 'ICS RF applicability 적용성',
    title: 'E-UTRA; UE conformance specification; Radio transmission and reception; Part 2: ICS',
    short: 'LTE RF test ICS',
    when: 'LTE RF applicability declaration.' },

  /* ── NTN study items (TR) ──────────────────────────── */
  { id: '38.811', m: 'rf', s: 'NR', rel: 'Rel-15', ntn: 'only', tr: true,
    kw: 'channel model scenario study NTN 위성 채널모델',
    title: 'Study on New Radio (NR) to support non-terrestrial networks',
    short: 'Study on NR to support NTN',
    when: 'NTN channel model과 scenario 정의의 출발점. 왜 이런 설계가 나왔는지의 배경.' },
  { id: '38.821', m: 'rf', s: 'NR', rel: 'Rel-16', ntn: 'only', tr: true,
    kw: 'transparent regenerative payload solutions study 투명 재생 페이로드',
    title: 'Solutions for NR to support non-terrestrial networks (NTN)',
    short: 'Solutions for NR to support NTN',
    when: '★ Rel-17 표준화 전 검토된 solution들. 현재 규격의 설계 근거를 추적할 때 가장 유용. <b>Transparent / regenerative payload 구분이 정의된 곳</b> — Rel-17 NR-NTN은 transparent payload만 규격화됐다.' },
  { id: '36.763', m: 'rf', s: 'LTE', rel: 'Rel-17', ntn: 'only', tr: true,
    kw: 'NB-IoT eMTC satellite study IoT NTN 위성',
    title: 'Study on Narrow-Band Internet of Things (NB-IoT) / enhanced Machine Type Communication (eMTC) support for Non-Terrestrial Networks (NTN)',
    short: 'Study on IoT NTN support',
    when: 'NB-IoT/eMTC의 satellite access 검토. IoT NTN 설계 배경.' }
];
