/* 3GPP UE 프로토콜 스펙 지도 — 데이터
 *
 * ntn 값: 'only'   = NTN 전용 문서
 *         'clause' = 일반 스펙인데 NTN 전용 조항이 있음
 *         null     = NTN 무관
 * side:   'ue' (기본) | 'net' = 망 측 문서(참고용)
 */

const MODULES = [
  { id: 'phy',    name: 'PHY',              desc: '물리계층 — 채널·부호화·절차·측정' },
  { id: 'mac',    name: 'MAC',              desc: '스케줄링, HARQ, 랜덤액세스' },
  { id: 'l2',     name: 'RLC · PDCP · SDAP', desc: 'L2 상위 — 재전송, 헤더압축·보안, QoS 매핑' },
  { id: 'rrc',    name: 'RRC · 이동성',      desc: '연결 제어, 셀 선택/재선택, 핸드오버, RRM' },
  { id: 'uecap',  name: 'UE 능력',           desc: '단말이 무엇을 지원한다고 말하는가' },
  { id: 'nas',    name: 'NAS · 코어 연동',   desc: '등록, 세션, 이동성 관리 — 코어망과의 대화' },
  { id: 'sec',    name: '보안 · USIM',       desc: '인증·키 유도, UICC/USIM 인터페이스' },
  { id: 'rf',     name: 'RF · 성능',         desc: '송수신 요구사항, 대역, 성능' },
  { id: 'ims',    name: 'IMS · 서비스',      desc: 'VoLTE/VoNR 호 제어와 미디어' },
  { id: 't-com',  name: '시험 — 공통환경',   desc: '시험 환경·설정의 공통 정의', test: true },
  { id: 't-pct',  name: '시험 — PCT',        desc: '프로토콜 적합성시험', test: true },
  { id: 't-rrm',  name: '시험 — RRM',        desc: '무선자원관리 적합성시험', test: true },
  { id: 't-rct',  name: '시험 — RCT',        desc: 'RF 적합성시험', test: true }
];

const SPECS = [
  /* ── PHY ───────────────────────────────────────────── */
  { id: '38.201', m: 'phy', s: 'NR', peer: '36.201', rel: 'Rel-15~',
    title: 'NR; Physical layer; General description',
    ko: '물리계층 총론',
    when: 'PHY 문서들(211~215)이 각각 무엇을 다루는지 길을 잃었을 때 돌아오는 지도.' },
  { id: '38.211', m: 'phy', s: 'NR', peer: '36.211', rel: 'Rel-15~',
    title: 'NR; Physical channels and modulation',
    ko: '물리채널과 변조',
    when: '프레임 구조, 뉴머롤로지, 자원격자, DMRS·SSB 위치를 확인할 때.' },
  { id: '38.212', m: 'phy', s: 'NR', peer: '36.212', rel: 'Rel-15~',
    title: 'NR; Multiplexing and channel coding',
    ko: '다중화와 채널부호화',
    when: 'DCI/UCI 필드 구성과 비트 크기, 폴라·LDPC 부호화 절차를 볼 때. DCI 포맷 파싱의 근거.' },
  { id: '38.213', m: 'phy', s: 'NR', peer: '36.213', rel: 'Rel-15~', ntn: 'clause',
    kw: 'RACH PRACH random access power control PUCCH beam TA timing advance K_offset',
    ntnNote: '<b>전송지연(시간축) 사전보상</b> — N<sub>TA,adjUE</sub> 기반 양방향 전파지연 보상, cellSpecificKoffset / K<sub>UE,offset</sub> 적용. <b>주파수(도플러) 사전보상은 여기가 아니라 38.300 §16.14.2.2</b>',
    title: 'NR; Physical layer procedures for control',
    ko: '제어용 물리계층 절차',
    when: '★ 랜덤액세스 절차, 전력제어, PUCCH 자원 결정, 빔 관리를 볼 때. NTN 타이밍 보정(TA·K_offset)도 여기 — 단 도플러는 38.300.' },
  { id: '38.214', m: 'phy', s: 'NR', peer: '36.213', rel: 'Rel-15~',
    title: 'NR; Physical layer procedures for data',
    ko: '데이터용 물리계층 절차',
    when: 'PDSCH/PUSCH 자원 할당, MCS·TBS 계산, CSI 보고 절차.' },
  { id: '38.215', m: 'phy', s: 'NR', peer: '36.214', rel: 'Rel-15~',
    title: 'NR; Physical layer measurements',
    ko: '물리계층 측정',
    when: 'RSRP/RSRQ/SINR의 정확한 정의가 필요할 때. 측정값 불일치 디버깅의 출발점.' },
  { id: '36.201', m: 'phy', s: 'LTE', peer: '38.201', rel: 'Rel-8~',
    title: 'E-UTRA; LTE physical layer; General description', ko: 'LTE 물리계층 총론',
    when: 'LTE PHY 문서 구성 파악용.' },
  { id: '36.211', m: 'phy', s: 'LTE', peer: '38.211', rel: 'Rel-8~',
    title: 'E-UTRA; Physical channels and modulation', ko: 'LTE 물리채널과 변조',
    when: 'LTE 프레임 구조, 참조신호, PSS/SSS. NB-IoT 물리채널(NPBCH·NPDCCH·NPUSCH)도 여기 포함.' },
  { id: '36.212', m: 'phy', s: 'LTE', peer: '38.212', rel: 'Rel-8~',
    title: 'E-UTRA; Multiplexing and channel coding', ko: 'LTE 다중화와 채널부호화',
    when: 'LTE DCI 포맷과 터보부호화. NB-IoT 부호화 포함.' },
  { id: '36.213', m: 'phy', s: 'LTE', peer: '38.213', rel: 'Rel-8~',
    title: 'E-UTRA; Physical layer procedures', ko: 'LTE 물리계층 절차',
    when: 'LTE는 제어/데이터 절차가 한 문서에 있다(NR은 38.213/38.214로 분리). 이 차이가 자주 헷갈린다.' },
  { id: '36.214', m: 'phy', s: 'LTE', peer: '38.215', rel: 'Rel-8~',
    title: 'E-UTRA; Physical layer; Measurements', ko: 'LTE 물리계층 측정',
    when: 'LTE RSRP/RSRQ 정의.' },

  /* ── MAC ───────────────────────────────────────────── */
  { id: '38.321', m: 'mac', s: 'NR', peer: '36.321', rel: 'Rel-15~', ntn: 'clause',
    ntnNote: 'NTN 랜덤액세스 적응 — 확장 RA 응답 윈도우, HARQ 비활성 옵션',
    title: 'NR; Medium Access Control (MAC) protocol specification',
    ko: 'MAC 프로토콜',
    when: '★ MAC PDU 포맷, LCID 값, BSR/PHR, DRX 타이머, RA 절차. 로그 분석에서 가장 자주 펼침.' },
  { id: '36.321', m: 'mac', s: 'LTE', peer: '38.321', rel: 'Rel-8~', ntn: 'clause',
    ntnNote: 'IoT NTN RA 적응(Rel-17~)',
    title: 'E-UTRA; Medium Access Control (MAC) protocol specification', ko: 'LTE MAC 프로토콜',
    when: 'LTE MAC PDU·LCID·DRX. NB-IoT DRX/eDRX 동작도 여기.' },

  /* ── RLC · PDCP · SDAP ─────────────────────────────── */
  { id: '38.322', m: 'l2', s: 'NR', peer: '36.322', rel: 'Rel-15~',
    title: 'NR; Radio Link Control (RLC) protocol specification', ko: 'RLC 프로토콜',
    when: 'AM/UM 동작, 상태보고, 재조립. NR RLC는 연결(concatenation)이 없다는 점이 LTE와 큰 차이.' },
  { id: '38.323', m: 'l2', s: 'NR', peer: '36.323', rel: 'Rel-15~',
    title: 'NR; Packet Data Convergence Protocol (PDCP) specification', ko: 'PDCP 프로토콜',
    when: '헤더압축(ROHC), 무결성보호·암호화, 순서재정렬, 중복전송(duplication).' },
  { id: '37.324', m: 'l2', s: 'NR', rel: 'Rel-15~',
    title: 'E-UTRA and NR; Service Data Adaptation Protocol (SDAP) specification', ko: 'SDAP 프로토콜',
    when: 'QoS 플로우 → DRB 매핑. <b>NR에만 있는 계층</b>이라 LTE 경험자가 처음 만나면 낯설다. 37.xxx 시리즈인 것도 주의.' },
  { id: '36.322', m: 'l2', s: 'LTE', peer: '38.322', rel: 'Rel-8~',
    title: 'E-UTRA; Radio Link Control (RLC) protocol specification', ko: 'LTE RLC 프로토콜',
    when: 'LTE RLC AM/UM. 연결(concatenation)이 있다는 점이 NR과 다르다.' },
  { id: '36.323', m: 'l2', s: 'LTE', peer: '38.323', rel: 'Rel-8~',
    title: 'E-UTRA; Packet Data Convergence Protocol (PDCP) specification', ko: 'LTE PDCP 프로토콜',
    when: 'LTE PDCP, ROHC.' },

  /* ── RRC · 이동성 ──────────────────────────────────── */
  { id: '38.300', m: 'rrc', s: 'NR', peer: '36.300', rel: 'Rel-15~', ntn: 'clause',
    kw: 'stage 2 overall description architecture Doppler frequency pre-compensation',
    ntnNote: '§16.14 NTN 전반. <b>§16.14.2.2 Timing Advance and Frequency Pre-compensation</b> — 단말이 위성 에페메리스와 자기 위치로 <b>도플러 천이를 스스로 계산해 상향 반송파를 사전보상</b>한다고 규정한 곳. 38.101-5 §6.4.1이 이 조항을 직접 참조한다.',
    title: 'NR; NR and NG-RAN Overall description; Stage-2', ko: 'NR·NG-RAN 총론 (Stage-2)',
    when: '★ 개별 계층 문서로 들어가기 전에 전체 구조를 잡는 문서. "이 기능이 어느 계층 소관인가"의 1차 답이 대개 여기. NTN 상향 동기의 규범적 출처.' },
  { id: '36.300', m: 'rrc', s: 'LTE', peer: '38.300', rel: 'Rel-8~',
    kw: 'stage 2 overall description architecture',
    title: 'E-UTRA and E-UTRAN; Overall description; Stage 2', ko: 'E-UTRA·E-UTRAN 총론 (Stage 2)',
    when: 'LTE 전체 구조 조망. 계층 간 기능 분담을 확인할 때.' },
  { id: '38.331', m: 'rrc', s: 'NR', peer: '36.331', rel: 'Rel-15~', ntn: 'clause',
    kw: 'RRC ASN.1 SIB SIB19 handover measurement reconfiguration',
    ntnNote: 'SIB19 / <code>NTN-Config-r17</code> — <code>ephemerisInfo</code>, <code>epochTime</code>, <code>ta-Info-r17</code>(하위 <code>ta-Common</code> / <code>ta-CommonDrift</code> / <code>ta-CommonDriftVariant</code>), <code>cellSpecificKoffset-r17</code>, <code>ntn-UlSyncValidityDuration</code>, <code>t-Service</code>, <code>referenceLocation</code>, <code>distanceThresh</code>, <code>ntn-PolarizationDL/UL</code>, <code>ntn-NeighCellConfigList</code>',
    title: 'NR; Radio Resource Control (RRC); Protocol specification', ko: 'RRC 프로토콜',
    when: '★★ 단말 개발에서 가장 자주 펼치는 문서. 모든 ASN.1 정의, SIB 구성, 측정 설정, 핸드오버 메시지가 여기.' },
  { id: '38.304', m: 'rrc', s: 'NR', peer: '36.304', rel: 'Rel-15~', ntn: 'clause',
    ntnNote: 'NTN 셀 선택/재선택 — 위치 기반 조건, 서비스 시간(t-Service) 고려',
    title: 'NR; User Equipment (UE) procedures in Idle mode and in RRC Inactive state',
    ko: 'Idle/Inactive 단말 절차',
    when: '셀 선택·재선택 기준(S 기준, R 기준), PLMN 선택, 페이징 수신 시점 계산.' },
  { id: '38.133', m: 'rrc', s: 'NR', peer: '36.133', rel: 'Rel-15~',
    title: 'NR; Requirements for support of radio resource management', ko: 'RRM 요구사항',
    when: '측정 정확도, 셀 식별 시간, 핸드오버 지연 요구. "얼마나 빨리/정확히" 해야 하는지의 근거. 38.533 시험의 뿌리.' },
  { id: '36.331', m: 'rrc', s: 'LTE', peer: '38.331', rel: 'Rel-8~', ntn: 'clause',
    ntnNote: 'IoT NTN 관련 SIB·설정(Rel-17~)',
    title: 'E-UTRA; Radio Resource Control (RRC); Protocol specification', ko: 'LTE RRC 프로토콜',
    when: 'LTE RRC ASN.1 전체. NB-IoT RRC도 이 문서 안에 포함.' },
  { id: '36.304', m: 'rrc', s: 'LTE', peer: '38.304', rel: 'Rel-8~',
    title: 'E-UTRA; User Equipment (UE) procedures in idle mode', ko: 'LTE Idle 단말 절차',
    when: 'LTE 셀 선택·재선택, 페이징.' },
  { id: '36.133', m: 'rrc', s: 'LTE', peer: '38.133', rel: 'Rel-8~',
    title: 'E-UTRA; Requirements for support of radio resource management', ko: 'LTE RRM 요구사항',
    when: 'LTE 측정·이동성 성능 요구. 36.521-3 시험의 뿌리.' },

  /* ── UE 능력 ───────────────────────────────────────── */
  { id: '38.306', m: 'uecap', s: 'NR', peer: '36.306', rel: 'Rel-15~',
    title: 'NR; User Equipment (UE) radio access capabilities', ko: 'UE 무선접속 능력',
    when: '★ 어떤 능력 파라미터가 있고 값의 의미가 무엇인지. featureSets / featureSetCombination 구조가 NR 능력의 핵심.',
    xref: '시그널링은 38.331(UECapabilityInformation), 시험 선언은 38.508-2(ICS)' },
  { id: '38.822', m: 'uecap', s: 'NR', rel: 'Rel-15~', tr: true,
    title: 'NR; User Equipment (UE) feature list', ko: 'NR UE 기능 목록',
    when: '릴리스별로 어떤 기능이 있고 어느 능력 파라미터에 대응하는지 훑을 때. TR이지만 실무 참조도가 높다.' },
  { id: '38.307', m: 'uecap', s: 'NR', peer: '36.307', rel: 'Rel-15~',
    title: 'NR; Requirements on User Equipments (UEs) supporting a release-independent frequency band',
    ko: '릴리스 독립 대역 지원 요구사항',
    when: '나중 릴리스에서 추가된 대역을 이전 릴리스 단말이 지원할 때의 규칙.' },
  { id: '36.306', m: 'uecap', s: 'LTE', peer: '38.306', rel: 'Rel-8~',
    title: 'E-UTRA; User Equipment (UE) radio access capabilities', ko: 'LTE UE 무선접속 능력',
    when: 'UE category와 능력 파라미터. NB-IoT 카테고리(NB1/NB2)도 여기.',
    xref: '시그널링은 36.331(UE-EUTRA-Capability)' },
  { id: '36.307', m: 'uecap', s: 'LTE', peer: '38.307', rel: 'Rel-8~',
    title: 'E-UTRA; Requirements on User Equipments (UEs) supporting a release-independent frequency band',
    ko: 'LTE 릴리스 독립 대역', when: 'LTE 대역 추가 시 릴리스 호환 규칙.' },

  /* ── NAS · 코어 ────────────────────────────────────── */
  { id: '24.501', m: 'nas', s: 'NR', peer: '24.301', rel: 'Rel-15~', ntn: 'clause',
    ntnNote: '5GS NTN 관련 절차·타이머 조정',
    title: 'Non-Access-Stratum (NAS) protocol for 5G System (5GS); Stage 3', ko: '5GS NAS 프로토콜',
    when: '★ 등록/PDU세션 절차, 5GMM·5GSM 메시지와 IE, 타이머(T3510 등). 5G 단말 NAS 개발의 본문.' },
  { id: '23.501', m: 'nas', s: 'NR', peer: '23.401', rel: 'Rel-15~', ntn: 'clause',
    ntnNote: '§5.4.10 위성 접속 식별·제한, §5.4.11 위성 접속의 5GS 통합 — 위성 RAT type, 망 선택, Tracking Area 처리, Forbidden/Service Area 이동성 제한. (투명/재생 페이로드 구분은 여기가 아니라 TR 38.821)',
    title: 'System architecture for the 5G System (5GS)', ko: '5GS 시스템 아키텍처',
    when: '용어와 개념의 출처. "이 기능이 왜 이렇게 설계됐나"를 물을 때.' },
  { id: '23.502', m: 'nas', s: 'NR', rel: 'Rel-15~',
    title: 'Procedures for the 5G System (5GS)', ko: '5GS 절차',
    when: '단말~기지국~코어를 잇는 end-to-end 호 흐름도. NAS 메시지가 어떤 맥락에서 오가는지 볼 때.' },
  { id: '24.301', m: 'nas', s: 'LTE', peer: '24.501', rel: 'Rel-8~', ntn: 'clause',
    ntnNote: 'IoT NTN 관련 타이머·절차 조정(Rel-17~)',
    title: 'Non-Access-Stratum (NAS) protocol for Evolved Packet System (EPS); Stage 3',
    ko: 'EPS NAS 프로토콜',
    when: '★ EMM/ESM 절차와 메시지. Attach·TAU·서비스요청. NB-IoT의 CIoT EPS 최적화(제어평면 CIoT)도 여기.' },
  { id: '23.401', m: 'nas', s: 'LTE', peer: '23.501', rel: 'Rel-8~',
    title: 'GPRS enhancements for E-UTRAN access', ko: 'EPS 시스템 아키텍처',
    when: 'EPS 베어러 개념, 인터페이스 정의.' },
  { id: '24.008', m: 'nas', s: '공통', rel: 'Rel-99~', base: true,
    title: 'Mobile radio interface Layer 3 specification; Core network protocols; Stage 3',
    ko: 'L3 코어망 프로토콜 · 공통 IE',
    when: '★ 24.301과 24.501이 IE 정의를 이 문서에서 참조해 온다. "이 IE 정의가 어디 있지?"의 답이 자주 여기. MM/GMM/CC/SM의 원형.' },
  { id: '23.122', m: 'nas', s: '공통', rel: 'Rel-99~',
    kw: 'PLMN selection forbidden PLMN manual search idle mode',
    title: 'Non-Access-Stratum (NAS) functions related to Mobile Station (MS) in idle mode',
    ko: 'Idle 모드 PLMN 선택',
    when: '★ PLMN 선택·재선택, 금지 PLMN 목록, 수동 검색의 본문. 24.301/24.501 다음으로 자주 펼치는 NAS 문서. 위성 접속 PLMN 선택도 여기.' },
  { id: '24.007', m: 'nas', s: '공통', rel: 'Rel-99~', base: true,
    title: 'Mobile radio interface signalling layer 3; General aspects',
    ko: 'L3 시그널링 일반 규칙',
    when: 'L3 메시지의 일반 포맷과 IE 부호화 규칙(T/L/V, TLV 등). 메시지 파서를 직접 만들 때의 근거.' },

  /* ── 보안 · USIM ───────────────────────────────────── */
  { id: '33.501', m: 'sec', s: 'NR', peer: '33.401', rel: 'Rel-15~',
    title: 'Security architecture and procedures for 5G System', ko: '5G 보안 아키텍처',
    when: '5G-AKA 인증, 키 계층(K_AUSF→K_SEAF→K_AMF→K_gNB), SUCI 은닉. NAS/AS 보안 활성화 절차.' },
  { id: '33.401', m: 'sec', s: 'LTE', peer: '33.501', rel: 'Rel-8~',
    title: '3GPP System Architecture Evolution (SAE); Security architecture', ko: 'EPS 보안 아키텍처',
    when: 'EPS-AKA, KASME 기반 키 유도.' },
  { id: '31.101', m: 'sec', s: '공통', rel: 'Rel-99~',
    title: 'UICC-terminal interface; Physical and logical characteristics', ko: 'UICC–단말 인터페이스',
    when: 'APDU 수준에서 UICC와 대화할 때.' },
  { id: '31.102', m: 'sec', s: '공통', rel: 'Rel-99~',
    title: 'Characteristics of the USIM application', ko: 'USIM 애플리케이션',
    when: '★ EF 파일 구조(EF_IMSI, EF_LOCI, EF_EPSLOCI 등), 인증 명령. 단말이 USIM에서 무엇을 읽는지.' },

  /* ── RF · 성능 ─────────────────────────────────────── */
  { id: '38.101-1', m: 'rf', s: 'NR', peer: '36.101', rel: 'Rel-15~',
    title: 'NR; UE radio transmission and reception; Part 1: Range 1 Standalone', ko: 'NR UE RF (FR1)',
    when: '대역 정의, 송신전력 등급, 수신감도. FR1(6GHz 이하) 대역 확인은 여기.' },
  { id: '38.101-2', m: 'rf', s: 'NR', rel: 'Rel-15~',
    title: 'NR; UE radio transmission and reception; Part 2: Range 2 Standalone', ko: 'NR UE RF (FR2)',
    when: 'mmWave 대역. FR1과 요구사항 체계가 다르다(EIRP 기반 등).' },
  { id: '38.101-3', m: 'rf', s: 'NR', rel: 'Rel-15~',
    title: 'NR; UE radio transmission and reception; Part 3: Range 1 and Range 2 Interworking with other radios',
    ko: 'NR UE RF (대역간 연동)', when: 'EN-DC 등 LTE-NR 동시 동작 시의 RF 요구사항.' },
  { id: '38.101-4', m: 'rf', s: 'NR', rel: 'Rel-15~',
    title: 'NR; UE radio transmission and reception; Part 4: Performance requirements',
    ko: 'NR UE 성능 요구사항', when: '복조 성능·CSI 보고 정확도 요구.' },
  { id: '38.101-5', m: 'rf', s: 'NR', rel: 'Rel-17~', ntn: 'only',
    title: 'NR; UE radio transmission and reception; Part 5: Satellite access Radio Frequency (RF) and performance requirements',
    ko: 'NTN 위성접속 UE RF·성능',
    when: 'NTN 전용. 위성 접속 단말의 RF·성능 요구사항 — 지상망과 별도 파트로 분리되어 있다.' },
  { id: '38.108', m: 'rf', s: 'NR', rel: 'Rel-17~', ntn: 'only', side: 'net',
    title: 'NR; Satellite Access Node radio transmission and reception', ko: 'NTN 위성 접속노드 RF',
    when: 'NTN 전용, 망 측 문서. 위성 페이로드 쪽 요구사항을 확인할 때.' },
  { id: '36.101', m: 'rf', s: 'LTE', peer: '38.101-1', rel: 'Rel-8~',
    title: 'E-UTRA; User Equipment (UE) radio transmission and reception', ko: 'LTE UE RF',
    when: 'LTE 대역·전력등급·감도. NB-IoT RF 요구사항도 이 문서에 포함.' },

  /* ── IMS · 서비스 ──────────────────────────────────── */
  { id: '24.229', m: 'ims', s: '공통', rel: 'Rel-5~',
    title: 'IP multimedia call control protocol based on SIP and SDP; Stage 3', ko: 'IMS SIP 호 제어',
    when: '★ VoLTE/VoNR 등록·호 설정 SIP 메시지. 매우 두껍고 IETF RFC를 대량 참조하므로 각오하고 펼칠 것.' },
  { id: '26.114', m: 'ims', s: '공통', rel: 'Rel-7~',
    title: 'IMS; Multimedia telephony; Media handling and interaction', ko: 'MTSI 미디어 처리',
    when: '코덱 협상, 지터버퍼, 미디어 적응. 음성 품질 이슈의 근거 문서.' },

  /* ── 시험 — 공통환경 ───────────────────────────────── */
  { id: '38.508-1', m: 't-com', s: 'NR', peer: '36.508', rel: 'Rel-15~',
    title: '5GS; UE conformance specification; Part 1: Common test environment', ko: 'NR 공통 시험환경',
    when: '★ 시험용 기준 설정·메시지 내용·공통 절차. PCT/RRM/RCT 셋이 모두 이 문서를 참조한다.' },
  { id: '38.508-2', m: 't-com', s: 'NR', rel: 'Rel-15~',
    title: '5GS; UE conformance specification; Part 2: Common Implementation Conformance Statement (ICS) proforma',
    ko: 'NR 공통 ICS',
    when: '단말이 "무엇을 지원한다"고 선언하는 표. 이 선언이 어떤 시험케이스가 적용될지를 결정한다.',
    xref: '능력 정의는 38.306' },
  { id: '36.508', m: 't-com', s: 'LTE', peer: '38.508-1', rel: 'Rel-8~',
    title: 'E-UTRA and EPC; Common test environments for UE conformance testing', ko: 'LTE 공통 시험환경',
    when: 'LTE 시험 공통 설정.' },

  /* ── 시험 — PCT ────────────────────────────────────── */
  { id: '38.523-1', m: 't-pct', s: 'NR', peer: '36.523-1', rel: 'Rel-15~',
    title: '5GS; UE conformance specification; Part 1: Protocol', ko: 'NR 프로토콜 시험케이스',
    when: '★ 시험케이스 본문. 단말 프로토콜 개발자가 시험 계열에서 가장 자주 보는 문서.' },
  { id: '38.523-2', m: 't-pct', s: 'NR', rel: 'Rel-15~',
    title: '5GS; UE conformance specification; Part 2: Applicability of protocol test cases',
    ko: 'NR 시험케이스 적용성', when: '어떤 단말에 어떤 시험이 적용되는지의 조건표.' },
  { id: '38.523-3', m: 't-pct', s: 'NR', rel: 'Rel-15~',
    title: '5GS; UE conformance specification; Part 3: Protocol Test Suites', ko: 'NR 시험 스위트(TTCN)',
    when: '실제 TTCN 구현. 시험 장비 동작을 추적할 때.' },
  { id: '36.523-1', m: 't-pct', s: 'LTE', peer: '38.523-1', rel: 'Rel-8~',
    title: 'E-UTRA and EPC; UE conformance specification; Part 1: Protocol conformance specification',
    ko: 'LTE 프로토콜 시험케이스', when: 'LTE 프로토콜 시험 본문.' },
  { id: '36.523-2', m: 't-pct', s: 'LTE', rel: 'Rel-8~',
    title: 'E-UTRA and EPC; UE conformance specification; Part 2: ICS proforma specification',
    ko: 'LTE 시험 ICS', when: 'LTE 적용성 선언.' },
  { id: '36.523-3', m: 't-pct', s: 'LTE', rel: 'Rel-8~',
    title: 'E-UTRA and EPC; UE conformance specification; Part 3: Test suites',
    ko: 'LTE 시험 스위트(TTCN)', when: 'LTE TTCN 구현.' },

  /* ── 시험 — RRM ────────────────────────────────────── */
  { id: '38.533', m: 't-rrm', s: 'NR', peer: '36.521-3', rel: 'Rel-15~', asym: true,
    title: 'NR; User Equipment (UE) conformance specification; Radio Resource Management (RRM)',
    ko: 'NR RRM 적합성시험',
    when: '★ 측정·이동성 성능 시험. <b>주의: NR은 RRM이 521 시리즈 밖으로 나와 별도 번호(38.533)를 쓴다.</b> LTE(36.521-3)와 체계가 다르다.',
    xref: '요구사항 본문은 38.133' },
  { id: '36.521-3', m: 't-rrm', s: 'LTE', peer: '38.533', rel: 'Rel-8~', asym: true,
    title: 'E-UTRA; UE conformance specification; Radio transmission and reception; Part 3: Radio Resource Management (RRM) conformance testing',
    ko: 'LTE RRM 적합성시험',
    when: 'LTE 측정·이동성 시험. <b>NR과 달리 521 시리즈 안에 들어 있다.</b>',
    xref: '요구사항 본문은 36.133' },

  /* ── 시험 — RCT ────────────────────────────────────── */
  { id: '38.521-1', m: 't-rct', s: 'NR', peer: '36.521-1', rel: 'Rel-15~',
    title: 'NR; UE conformance specification; Radio transmission and reception; Part 1: Range 1 Standalone',
    ko: 'NR RF 시험 (FR1)', when: 'FR1 RF 적합성시험.', xref: '요구사항 본문은 38.101-1' },
  { id: '38.521-2', m: 't-rct', s: 'NR', rel: 'Rel-15~',
    title: 'NR; UE conformance specification; Radio transmission and reception; Part 2: Range 2 Standalone',
    ko: 'NR RF 시험 (FR2)', when: 'FR2 RF 적합성시험.', xref: '요구사항 본문은 38.101-2' },
  { id: '38.521-3', m: 't-rct', s: 'NR', rel: 'Rel-15~',
    title: 'NR; UE conformance specification; Radio transmission and reception; Part 3: Range 1 and Range 2 Interworking operation with other radios',
    ko: 'NR RF 시험 (연동)', when: 'EN-DC 등 연동 RF 시험.', xref: '요구사항 본문은 38.101-3' },
  { id: '38.521-4', m: 't-rct', s: 'NR', rel: 'Rel-15~',
    title: 'NR; UE conformance specification; Radio transmission and reception; Part 4: Performance',
    ko: 'NR 성능 시험', when: '복조 성능 시험.', xref: '요구사항 본문은 38.101-4' },
  { id: '38.521-5', m: 't-rct', s: 'NR', rel: 'Rel-17~', ntn: 'only',
    title: 'NR; UE conformance specification; Radio transmission and reception; Part 5: Satellite access Radio Frequency (RF) and performance requirements',
    ko: 'NTN 위성접속 RF 시험',
    when: 'NTN 전용. 38.101-5의 시험 짝 — 위성 접속 단말의 RF·성능 적합성시험.',
    xref: '요구사항 본문은 38.101-5' },
  { id: '36.521-1', m: 't-rct', s: 'LTE', peer: '38.521-1', rel: 'Rel-8~',
    title: 'E-UTRA; UE conformance specification; Radio transmission and reception; Part 1: Conformance testing',
    ko: 'LTE RF 시험', when: 'LTE RF 적합성시험.', xref: '요구사항 본문은 36.101' },
  { id: '36.521-2', m: 't-rct', s: 'LTE', rel: 'Rel-8~',
    title: 'E-UTRA; UE conformance specification; Radio transmission and reception; Part 2: ICS',
    ko: 'LTE RF 시험 ICS', when: 'LTE RF 적용성 선언.' },

  /* ── NTN 연구 문서 (TR) ────────────────────────────── */
  { id: '38.811', m: 'rf', s: 'NR', rel: 'Rel-15', ntn: 'only', tr: true,
    title: 'Study on New Radio (NR) to support non-terrestrial networks', ko: 'NR NTN 지원 연구',
    when: 'NTN 채널 모델과 시나리오 정의의 출발점. 왜 이런 설계가 나왔는지의 배경.' },
  { id: '38.821', m: 'rf', s: 'NR', rel: 'Rel-16', ntn: 'only', tr: true,
    title: 'Solutions for NR to support non-terrestrial networks (NTN)', ko: 'NR NTN 솔루션 연구',
    when: '★ Rel-17 표준화 전 검토된 해법들. 현재 규격의 설계 근거를 추적할 때 가장 유용. <b>투명(transparent)/재생(regenerative) 페이로드 구분이 정의된 곳</b> — Rel-17 NR-NTN은 투명 페이로드만 규격화됐다.' },
  { id: '36.763', m: 'rf', s: 'LTE', rel: 'Rel-17', ntn: 'only', tr: true,
    title: 'Study on Narrow-Band Internet of Things (NB-IoT) / enhanced Machine Type Communication (eMTC) support for Non-Terrestrial Networks (NTN)',
    ko: 'IoT NTN 지원 연구',
    when: 'NB-IoT/eMTC의 위성 접속 검토. IoT NTN 설계 배경.' }
];
